// File generated by FlutterFire CLI — do not edit manually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdEOBqFFeS9eyw_bTt6GIdwkjKtB7c3gk',
    appId: '1:645366167801:android:99957d48f6192ffef5ca28',
    messagingSenderId: '645366167801',
    projectId: 'testproject1-489910',
    storageBucket: 'testproject1-489910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn5AMjaK6quMMt51_2HTnc4O7_ayQKtwc',
    appId: '1:645366167801:ios:ff441ab766e4275ff5ca28',
    messagingSenderId: '645366167801',
    projectId: 'testproject1-489910',
    storageBucket: 'testproject1-489910.firebasestorage.app',
    iosBundleId: 'com.forestshoes.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn5AMjaK6quMMt51_2HTnc4O7_ayQKtwc',
    appId: '1:645366167801:ios:ff441ab766e4275ff5ca28',
    messagingSenderId: '645366167801',
    projectId: 'testproject1-489910',
    storageBucket: 'testproject1-489910.firebasestorage.app',
    iosBundleId: 'com.forestshoes.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHeDvbLwlqaxdVv4FViDe2jAHPG3B38GU',
    appId: '1:645366167801:web:619b7bfa10008ac1f5ca28',
    messagingSenderId: '645366167801',
    projectId: 'testproject1-489910',
    storageBucket: 'testproject1-489910.firebasestorage.app',
    authDomain: 'testproject1-489910.firebaseapp.com',
  );
}
